<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd0c315d4e74a3521f110a8df177ffd60
{
    public static $files = array (
        '04c6c5c2f7095ccf6c481d3e53e1776f' => __DIR__ . '/..' . '/mustangostang/spyc/Spyc.php',
    );

    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DeviceDetector\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DeviceDetector\\' => 
        array (
            0 => __DIR__ . '/..' . '/matomo/device-detector',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd0c315d4e74a3521f110a8df177ffd60::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd0c315d4e74a3521f110a8df177ffd60::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd0c315d4e74a3521f110a8df177ffd60::$classMap;

        }, null, ClassLoader::class);
    }
}
